Repository Student-Center/weave-ios, pull requests merged in 2024-02, with the labels that each got.

#2 [WEAV-157] 네트워크 레이어
  weave-iOS/Projects/App/Project.swift
  weave-iOS/Projects/App/Sources/WeaveApp.swift
  weave-iOS/Projects/App/Support/weave-ios-Info.plist
  weave-iOS/Projects/Core/Sources/Network/Common/NetworkError.swift
  weave-iOS/Projects/Core/Sources/Network/Common/ServerType.swift
  weave-iOS/Projects/Core/Sources/Network/Endpoint/EndPoint.swift
  weave-iOS/Projects/Core/Sources/Network/Endpoint/Requestable.swift
  weave-iOS/Projects/Core/Sources/Network/Endpoint/Responsable.swift
  weave-iOS/Projects/Core/Sources/Network/Provider/Provider.swift
  weave-iOS/Projects/Core/Sources/Network/Sample/APIEndpoints.swift
  weave-iOS/Projects/Core/Sources/Network/Sample/NetworkSample.swift
Labels: feature

#3 [인프라] DesignSystem 에 Icon 디렉토리 추가
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Common/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Common/appLogo.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Common/appLogo.imageset/Title@2x.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Contents.json
Labels: design

#5 [인프라] App Info.plist 수정 - LaunchScreen Key 추가
  weave-iOS/Projects/App/Support/weave-ios-Info.plist
Labels: infra

#6 [WEAV-157] 네트워크 모듈 접근제어자 수정, async/await request 추가
  weave-iOS/Projects/Core/Sources/Network/Endpoint/EndPoint.swift
  weave-iOS/Projects/Core/Sources/Network/Endpoint/Requestable.swift
  weave-iOS/Projects/Core/Sources/Network/Endpoint/Responsable.swift
  weave-iOS/Projects/Core/Sources/Network/Provider/Provider.swift
  weave-iOS/Projects/Core/Sources/Network/Sample/APIEndpoints.swift
Labels: feature, infra

#9 [Infra] 번들 ID 변경
  weave-iOS/Projects/App/Project.swift
  weave-iOS/Projects/Core/Project.swift
  weave-iOS/Projects/DesignSystem/Project.swift
Labels: infra

#10 [WEAV-157] URLSession async await request 이슈 수정
  weave-iOS/Projects/Core/Sources/Network/Provider/Provider.swift
Labels: bugfix

#11 [Infra] Network base url, 보안 적용
  weave-iOS/Projects/Core/Sources/Network/Common/SecretKey.swift
  weave-iOS/Projects/Core/Sources/Network/Common/ServerType.swift
  weave-iOS/Projects/Core/Sources/Network/Endpoint/EndPoint.swift
  weave-iOS/Projects/Core/Sources/Network/Provider/Provider.swift
Labels: fix, infra

#14 [ Infra] Core, DesignSystem 모듈 Deployment Target Version 추가
  weave-iOS/Projects/Core/Project.swift
  weave-iOS/Projects/DesignSystem/Project.swift
Labels: infra

#15 [WEAV-159] 카카오 로그인 추가 구현
  weave-iOS/Projects/App/Sources/Login/KakaoLoginButton.swift
  weave-iOS/Projects/App/Sources/Login/LoginView.swift
Labels: fix, feature

#12 [WEAV-201] 마이페이지
  weave-iOS.textClipping
  weave-iOS/Projects/App/Sources/MyPage/Feature/MyPageFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/Model/Network/Domain/MyPageCategoryTypes.swift
  weave-iOS/Projects/App/Sources/MyPage/Model/Network/Domain/MyUserInfoModel.swift
  weave-iOS/Projects/App/Sources/MyPage/Model/Network/ResponseDTO/MyUserInfoResponseDTO.swift
  weave-iOS/Projects/App/Sources/MyPage/View/MyPageView.swift
  weave-iOS/Projects/App/Support/weave-ios-Info.plist
  weave-iOS/Projects/Core/Sources/Network/Provider/Provider.swift
  weave-iOS/Projects/DesignSystem/Resources/Colors/Colors.xcassets/TextGray.colorset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/certified.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/certified.imageset/certified.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/e-mail.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/e-mail.imageset/e-mail.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/footprint.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/footprint.imageset/footprint.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/icon_kakao.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/icon_kakao.imageset/icon_kakao.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/non-certified.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/non-certified.imageset/non-certified.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/profile_edit.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/profile_edit.imageset/edit2.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/profile_image.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/profile_image.imageset/profile.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/puzzle.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/puzzle.imageset/puzzle.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/ruler.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/ruler.imageset/ruler.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/setting.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/setting.imageset/setting.png
  weave-iOS/Projects/DesignSystem/Sources/Gradient/WeaveGradient.swift
  weave-iOS/Projects/DesignSystem/Sources/PhotoPicker/CameraView.swift
  weave-iOS/Projects/DesignSystem/Sources/PhotoPicker/PhotoPickerView.swift
Labels: feature

#16 [FEAT] 회원가입 뷰 인터페이스 구현
  weave-iOS/Projects/App/Sources/SignUp/Feature/SignUpFeature.swift
  weave-iOS/Projects/App/Sources/SignUp/View/SignUpView.swift
Labels: fix

#17 [Weav 159] Apple Login 추가
  weave-iOS/Projects/App/Project.swift
  weave-iOS/Projects/App/Sources/Login/AppleLoginButton.swift
  weave-iOS/Projects/App/Sources/Login/LoginView.swift
  weave-iOS/Projects/App/weave-ios.entitlements
Labels: feature

#18 [WEAV-248] 홈 탭바 구현
  weave-iOS/Projects/App/Sources/ContentView.swift
  weave-iOS/Projects/App/Sources/Navigation/AppScreen.swift
  weave-iOS/Projects/App/Sources/Navigation/AppTabView.swift
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/chat.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/chat.imageset/chat.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/home.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/home.imageset/home.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/myPage.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/myPage.imageset/user.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/myTeam.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/myTeam.imageset/team.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/request.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Navigation/request.imageset/request.png
Labels: feature

#19 [WEAV-249] 로그인, 홈 분기 및 탭뷰 목업뷰 추가
  weave-iOS/Projects/App/Sources/Chat/ChatView.swift
  weave-iOS/Projects/App/Sources/ContentView.swift
  weave-iOS/Projects/App/Sources/Home/HomeView.swift
  weave-iOS/Projects/App/Sources/MyTeam/MyTeamView.swift
  weave-iOS/Projects/App/Sources/Navigation/AppScreen.swift
  weave-iOS/Projects/App/Sources/Request/RequestView.swift
  weave-iOS/Projects/App/Sources/UDManager.swift
  weave-iOS/Projects/App/Sources/WeaveApp.swift
Labels: feature, infra

#21 [FIX] MBTI 재사용 가능한 형태 리팩토링
  weave-iOS/Projects/App/Sources/SignUp/Feature/SignUpFeature.swift
  weave-iOS/Projects/App/Sources/SignUp/View/StepSubViews/SignUpMBTIView.swift
  weave-iOS/Projects/DesignSystem/Sources/MBTIPicker/MBTIDataModel.swift
  weave-iOS/Projects/DesignSystem/Sources/MBTIPicker/MBTIPickerView.swift
Labels: refactor

#20 [WEAV-239] 대학교 인증 구현
  .gitignore
  weave-iOS/Projects/App/Sources/MyPage/Profile/Feature/MyPageFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/Profile/Model/Network/Domain/MyPageCategoryTypes.swift
  weave-iOS/Projects/App/Sources/MyPage/Profile/Model/Network/Domain/MyUserInfoModel.swift
  weave-iOS/Projects/App/Sources/MyPage/Profile/Model/Network/ResponseDTO/MyUserInfoResponseDTO.swift
  weave-iOS/Projects/App/Sources/MyPage/Profile/View/MyPageView.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/Feature/UnivEmailInputFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/Feature/UnivEmailVerifyFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/Model/Domain/UniversityInfoModel.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/Model/Network/EmailSendRequestDTO.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/Model/Network/EmailVerifyRequestDTO.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/Model/Network/UniversityInfoResponseDTO.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/View/UnivEmailInputView.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/View/UnivEmailVerifyView.swift
  weave-iOS/Projects/Core/Sources/Network/Provider/Provider.swift
  weave-iOS/Projects/DesignSystem/Resources/Colors/Colors.xcassets/NotificationRed.colorset/Contents.json
  weave-iOS/Projects/DesignSystem/Sources/VerifyCodeInput/VerifyCodeInputView.swift
Labels: feature

#22 [WEAV-240] 마이페이지 프로필 편집
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/Animals/AnimalTypes.swift
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/Animals/MyAnimalRequestDTO.swift
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/Animals/MyAnimalSelectionFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/Animals/MyAnimalSelectionView.swift
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/MBTI/Feature/MyMbtiEditFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/MBTI/Model/MyMbtiEditRequestDTO.swift
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/MBTI/View/MyMbtiEditView.swift
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/MyHeight/Feature/MyHeightEditFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/MyHeight/Model/MyHeightEditRequestDTO.swift
  weave-iOS/Projects/App/Sources/MyPage/EditProfile/MyHeight/View/MyHeightEditView.swift
  weave-iOS/Projects/App/Sources/MyPage/Feature/MyPageFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/Model/Network/ResponseDTO/MyUserInfoResponseDTO.swift
  weave-iOS/Projects/App/Sources/MyPage/View/MyPageView.swift
  weave-iOS/Projects/App/Sources/WeaveApp.swift
  weave-iOS/Projects/Core/Sources/Network/Endpoint/EndPoint.swift
  weave-iOS/Projects/Core/Sources/Network/Endpoint/Requestable.swift
  weave-iOS/Projects/Core/Sources/Network/Provider/Provider.swift
  weave-iOS/Projects/DesignSystem/Sources/Button/WeaveButton.swift
  weave-iOS/Projects/DesignSystem/Sources/Header/CenterTitleView.swift
  weave-iOS/Projects/DesignSystem/Sources/LeftAlignList/LeftAlignListFetchable.swift
  weave-iOS/Projects/DesignSystem/Sources/LeftAlignList/LeftAlignTextCapsuleListView.swift
  weave-iOS/Projects/DesignSystem/Sources/MBTIPicker/MBTIDataModel.swift
Labels: feature
