Repository Student-Center/weave-ios, pull requests merged in 2024-04, with the labels that each got.

#50 [Infra] AppCoordinator를 TCA Dependency로 전환, TabViewCoordinator 생성
  weave-iOS/Projects/App/Sources/AppView/AppView.swift
  weave-iOS/Projects/App/Sources/Chat/Feature/MatchedMeetingListFeature.swift
  weave-iOS/Projects/App/Sources/Chat/View/MatchedMeetingListView.swift
  weave-iOS/Projects/App/Sources/Home/View/MeetingTeamListView.swift
  weave-iOS/Projects/App/Sources/Login/LoginView.swift
  weave-iOS/Projects/App/Sources/MyPage/Profile/Feature/MyPageFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/Setting/Feature/SettingFeautre.swift
  weave-iOS/Projects/App/Sources/MyPage/Setting/View/SettingView.swift
  weave-iOS/Projects/App/Sources/MyTeam/View/GenerateMyTeamView.swift
  weave-iOS/Projects/App/Sources/MyTeam/View/MyTeamView.swift
  weave-iOS/Projects/App/Sources/Navigation/AppScreen.swift
  weave-iOS/Projects/App/Sources/Navigation/AppTabView.swift
  weave-iOS/Projects/App/Sources/Navigation/AppTabViewFeature.swift
  weave-iOS/Projects/App/Sources/Navigation/Dependency/TabViewCoordinatorKey.swift
  weave-iOS/Projects/App/Sources/Request/Feature/RequestListFeature.swift
  weave-iOS/Projects/App/Sources/Request/View/RequestListView.swift
  weave-iOS/Projects/App/Sources/SignUp/Feature/SignUpFeature.swift
  weave-iOS/Projects/App/Sources/SignUp/View/SignUpView.swift
Labels: infra

#47 [WEAV-241] 디자인시스템 WeaveToast 추가
  weave-iOS/Projects/App/Sources/AppView/AppView.swift
  weave-iOS/Projects/App/Sources/Login/LoginView.swift
  weave-iOS/Projects/App/Sources/MyPage/Setting/Feature/SettingFeautre.swift
  weave-iOS/Projects/App/Sources/MyPage/Setting/Model/SettingCategoryTypes.swift
  weave-iOS/Projects/App/Sources/MyPage/Setting/View/SettingView.swift
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/Setting/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/Setting/copyID.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/Setting/copyID.imageset/Icon-2.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/Setting/copyID.imageset/Icon-3.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/MyPage/Setting/copyID.imageset/Icon.png
  weave-iOS/Projects/DesignSystem/Sources/Toast/WeaveToast.swift
  weave-iOS/Projects/DesignSystem/Sources/Toast/WeaveToastExample.swift
  weave-iOS/Projects/DesignSystem/Sources/Toast/WeaveToastModifier.swift
Labels: design

#51 [WEAV-241] 앱 설정화면 추가작업
  weave-iOS/Projects/App/Sources/MyPage/Setting/View/SettingView.swift
Labels: feature

#54 [Fix] 미팅 리스트의 필터 적용 구조 변경
  weave-iOS/Projects/App/Sources/Home/Feature/MeetingTeamListFilterFeature.swift
  weave-iOS/Projects/App/Sources/Home/View/MeetingTeamListFilterView.swift
  weave-iOS/Projects/Core/Sources/Network/Endpoint/Requestable.swift
Labels: fix

#55 [Fix] UI Design 이슈 수정
  weave-iOS/Projects/App/Sources/Chat/Model/Network/MatchedMeetingTeamResponseDTO.swift
  weave-iOS/Projects/App/Sources/Chat/View/MatchedMeetingListView.swift
  weave-iOS/Projects/App/Sources/Chat/View/MeetingMatchProfileView.swift
  weave-iOS/Projects/App/Sources/Home/Feature/MeetingTeamDetailFeature.swift
  weave-iOS/Projects/App/Sources/Home/Model/Network/MeetingTeamDetailResponseDTO.swift
  weave-iOS/Projects/App/Sources/Home/View/MeetingTeamListView.swift
  weave-iOS/Projects/App/Sources/MyPage/Profile/Feature/MyPageFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/Profile/View/MyPageView.swift
  weave-iOS/Projects/App/Sources/MyPage/Setting/View/SettingView.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/Feature/UnivEmailInputFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/View/UnivEmailInputView.swift
  weave-iOS/Projects/App/Sources/MyTeam/Feature/MyTeamFeature.swift
  weave-iOS/Projects/App/Sources/MyTeam/View/MyTeamView.swift
  weave-iOS/Projects/App/Sources/Navigation/AppTabViewFeature.swift
  weave-iOS/Projects/App/Sources/Request/Feature/MeetingMatchFeature.swift
  weave-iOS/Projects/App/Sources/Request/View/MeetingMatchView.swift
  weave-iOS/Projects/App/Sources/Request/View/RequestListView.swift
  weave-iOS/Projects/DesignSystem/Sources/UserProfileBoxView/UserProfileBoxView.swift
Labels: bugfix, fix

#57 [WEAV-328] 웹 카카오 로그인 지원, 앱/로그인 Feature 구조 변경
  weave-iOS/Projects/App/Sources/AppView/AppViewFeature.swift
  weave-iOS/Projects/App/Sources/Login/KakaoLoginButton.swift
  weave-iOS/Projects/App/Sources/Login/LoginFeature.swift
  weave-iOS/Projects/App/Sources/SignUp/Feature/SignUpFeature.swift
  weave-iOS/Projects/App/Sources/UserInfo/UserInfo.swift
  weave-iOS/Projects/App/Support/weave-ios-Info.plist
Labels: fix

#59 [WEAV-332] 미팅팀 없을 때 필터 재설정 안내 뷰 구현
  weave-iOS/Projects/App/Sources/Chat/View/MatchedMeetingListView.swift
  weave-iOS/Projects/App/Sources/Home/View/MeetingTeamListView.swift
  weave-iOS/Projects/App/Sources/MyTeam/View/MyTeamView.swift
  weave-iOS/Projects/App/Sources/Request/View/RequestListView.swift
  weave-iOS/Projects/DesignSystem/Sources/ListEmptyGuideView/ListEmptyGuideView.swift
Labels: refactor, feature

#60 [WEAV-324] 로딩 인디케이터 구현
  weave-iOS/Projects/App/Sources/Chat/Feature/MatchedMeetingListFeature.swift
  weave-iOS/Projects/App/Sources/Chat/View/MatchedMeetingListView.swift
  weave-iOS/Projects/App/Sources/Home/Feature/MeetingTeamListFeature.swift
  weave-iOS/Projects/App/Sources/Home/View/MeetingTeamListView.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/Feature/UnivEmailInputFeature.swift
  weave-iOS/Projects/App/Sources/MyPage/UnivVerification/View/UnivEmailInputView.swift
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Indicator/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Indicator/Frame 1.imageset/1.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Indicator/Frame 1.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Indicator/Frame 2.imageset/2.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Indicator/Frame 2.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Indicator/Frame 3.imageset/3.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Indicator/Frame 3.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Indicator/Frame 4.imageset/4.png
  weave-iOS/Projects/DesignSystem/Resources/Icons/Icons.xcassets/Indicator/Frame 4.imageset/Contents.json
  weave-iOS/Projects/DesignSystem/Sources/WeaveIndicator/WeaveIndicator.swift
  weave-iOS/Projects/DesignSystem/Sources/WeaveIndicator/WeaveIndicatorModifier.swift
Labels: refactor, feature, design

#68 [Infra] default language 속성, 앱 버전 업데이트
  weave-iOS/Projects/App/Project.swift
  weave-iOS/Projects/App/Support/weave-ios-Info.plist
Labels: infra

#69 [ Feat] 팀 리스트 비었을 때 앱 공유 메시지 기능 추가
  weave-iOS/Projects/App/Sources/Constant/AppConstant.swift
  weave-iOS/Projects/App/Sources/Home/Feature/MeetingTeamListFeature.swift
  weave-iOS/Projects/App/Sources/Home/View/MeetingTeamListView.swift
Labels: feature

#72 [Doc] Readme 추가
  README.md
Labels: docs
